dist: trusty

services:
  - docker

install:
  - eval "$(ssh-agent -s)"
  - make setup
  - docker-compose up -d

script:
 - docker-compose run php composer install
 - make test.unit.run
 - make test.newman.run
